[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
# for displaying the web page
yew = "0.19"
yew-router = "0.16"

# core game types and AI logic
scrabble = { path = "../scrabble" }

# for communicating with api
api = { path = "../api" }
serde = "1.0"
serde_json = "1.0"
reqwasm = "0.4.0"
lazy_static = "1.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
