[package]
name = "scrabble"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
getrandom = { version = "0.2.5", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
bincode = "*"

[profile.dev]
opt-level =2 
