[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.1"
sqlx = { version = "0.5", features = [ "sqlite", "runtime-tokio-rustls" ] }
dotenv = "0.15.0"
anyhow = "1.0.45"

     