[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
# for the API
rocket = "0.5.0-rc.1"
# for interacting with sqlite
sqlx = { version = "0.5", features = [ "sqlite", "runtime-tokio-rustls" ] }
# for loading config in `.env` file
dotenv = "0.15.0"
# error handling
anyhow = "1.0.45"
# random number generation
fastrand = "1.5.0"
# logging
log = "0.4.0"
env_logger = "0.8.4"
