Table tbl_user {
  id_user Uuid [pk]
  username text
  email text
  hashed_pass text
  role text
  is_private bool
}

Table tbl_friend {
  first_id_user Uuid [pk, ref: > tbl_user.id_user]
  second_id_user Uuid [pk, ref: > tbl_user.id_user]
  date_added timestamp
}

Table tbl_friend_request {
  from_id_user Uuid [pk, ref: > tbl_user.id_user]
  to_id_user Uuid [pk, ref: > tbl_user.id_user]
  date_sent timestamp
}

Table tbl_player {
  id_player integer [pk]
  id_game Uuid [ref: > tbl_game.id_game]
  id_user Uuid [ref: > tbl_user.id_user]
  initial_rack text
  ai_difficulty text
  final_score int
  is_winner bool
}

Table tbl_game {
  id_game Uuid [pk]
  start datetime
  end datetime
  is_over bool
}

Table tbl_play {
  id_play int [pk]
  id_player int [ref: > tbl_player.id_player]
  letters_added text
  score int
}

Table tbl_tile {
  id_tile int [pk]
  id_play int [ref: > tbl_play.id_play]
  pos int
  letter char
  is_blank bool
}

Table tbl_word {
  id_word int [pk]
  id_play int [ref: > tbl_play.id_play]
  score int
  letters text
}

Table tbl_password_reset {
  id_user Uuid [pk, ref: > tbl_user.id_user]
  secret_hex TEXT
  valid_until timestamp
}
