[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
scrabble = { path = "../scrabble" }
chrono = { version = "0.4.19", features = ["serde"] }
